version: '3.8'

services:
  db:
    container_name: postgres-container
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api-production:
    container_name: api-container-production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: api_node
    restart: always
    command: sh -c "npx typeorm -d ./dist/database/data-source.js migration:run && npm start"
    volumes:
      - ./dist:/app/dist
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
      EXTERNAL_API: ${EXTERNAL_API}
      PORT: 3000
volumes:
  db:
    driver: local
networks:
  backend:
    driver: default